---
- name: Install and start Apache web server
  hosts: webservers
  become: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Write the Apache config file
      template:
        src: /path/to/httpd.conf.j2
        dest: /etc/httpd.conf

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_facts['os_family'] == "RedHat"
